#rm(list = ls(all = TRUE))

#install the following packages if required!
if(!("sp" %in% rownames(installed.packages())))
  install.packages("sp")
if(!("INLA" %in% rownames(installed.packages())))
  install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
if(!("bigmemory" %in% rownames(installed.packages())))
  install.packages("bigmemory")
if(!("ade4" %in% rownames(installed.packages())))
  install.packages("ade4")
if(!("hash" %in% rownames(installed.packages())))
  install.packages("hash")
if(!("speedglm" %in% rownames(installed.packages())))
  install.packages("speedglm")
if(!("stringi" %in% rownames(installed.packages())))
  install.packages("stringi")
if(!("biglm" %in% rownames(installed.packages())))
  install.packages("biglm")
if(!("glmnet" %in% rownames(installed.packages())))
  install.packages("glmnet")
if(!("BAS" %in% rownames(installed.packages())))
  install.packages("https://github.com/aliaksah/EMJMCMC2016/blob/master/examples/BAS%20archive/BAS_0.91.tar.gz?raw=true", repos = NULL)
if(!("BAS" %in% rownames(installed.packages())))
  install.packages("BAS")
if(!("MASS" %in% rownames(installed.packages())))
  install.packages("MASS")
if(!("parallel" %in% rownames(installed.packages())))
  install.packages("parallel")
if(!("stats" %in% rownames(installed.packages())))
  install.packages("stats")
#if(!("inline" %in% rownames(installed.packages())))
#  install.packages("inline")
if(!("RCurl" %in% rownames(installed.packages())))
  install.packages("RCurl")
if(!("gnlm" %in% rownames(installed.packages())))
  install.packages("gnlm")
#library(inline)
library(gnlm)
library(glmnet)
library(biglm)
library(hash)
library(sp)
library(INLA)
library(parallel)
library(bigmemory)
library(MASS)
library(ade4)
library(BAS)# should be version 0.9 !!!! otherwise some dependencies might not work!
library(stringi)
require(stats)
