# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# ======================================================== #
# Determines when the action is triggered                  #
# ======================================================== #

on: [push, pull_request]
name: linter

# ======================================================== #
# Determine actions to take                                #
# ======================================================== #

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checking out the repository
          uses: actions/checkout@v2

        - name: Setting up R
          uses: r-lib/actions/setup-r@v1

        - name: Installing legacy package dependencies
          run: install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE) # TEMP
          shell: Rscript {0}

        - name: Installing package dependencies
          run: |
            pack <- c(
              "glmnet", "biglm", "hash", "BAS", "stringi", "parallel",
              "methods", "speedglm", "stats"
            )
            install.packages(c(pack, "lintr", "devtools"))
          shell: Rscript {0}

        - name: Installing EMJMCMC
          run: Rscript -e 'devtools::install()'

        - name: Picking on the coding style
          run: |
            library(lintr)
            style_rules <- list(
              closed_curly_linter, todo_comment_linter, equals_na_linter,
              function_left_parentheses_linter, no_tab_linter, open_curly_linter,
              absolute_path_linter, nonportable_path_linter,
              pipe_continuation_linter, semicolon_terminator_linter,
              single_quotes_linter, trailing_blank_lines_linter, trailing_whitespace_linter,
              undesirable_function_linter, undesirable_operator_linter
            ) # TODO: expand style rules as package matures
            lint_package(linters = style_rules)
          shell: Rscript {0}
